In [46]:
import torch 

In [47]:
torch.cuda.is_available()

False

In [48]:
torch.cuda.device_count()

0

## Tensor

scaler 0D tensor
vectors 1D Tensor 
Matrices 2D tesor
Higer Dimmesntinal Tensor 3D +

In [49]:
data  = [1.0 ,2.0,3.0,4.0]

In [50]:
data

[1.0, 2.0, 3.0, 4.0]

In [51]:
tensor_from_list = torch.Tensor(data)

In [52]:
type(tensor_from_list)

torch.Tensor

In [53]:
tensor_from_list

tensor([1., 2., 3., 4.])

In [54]:
zeroes_tensor =  torch.zeros(3,3
                             )

In [55]:
zeroes_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [56]:
zeroes_tensor.ndim

2

In [57]:
ones_tensor = torch.ones(2,5)

In [58]:
ones_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [59]:
ones_tensor.ndim

2

In [60]:
random_tensor =torch.rand(4,4)

In [61]:
random_tensor

tensor([[0.7083, 0.3741, 0.6448, 0.8692],
        [0.9933, 0.9626, 0.8718, 0.5630],
        [0.3196, 0.8288, 0.7866, 0.4480],
        [0.5829, 0.7129, 0.4811, 0.1243]])

In [62]:
range_tensor = torch.arange(0,10)

In [63]:
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
import numpy as np

In [66]:
numpy_array = np.array([[1, 2,3, 4]])

In [67]:
tensor_from_np = torch.tensor(numpy_array)

In [68]:
tensor_from_np

tensor([[1, 2, 3, 4]])

In [69]:
float_tensor = torch.tensor([1.0, 2.0, 3.0],dtype=torch.float32)

In [70]:
float_tensor

tensor([1., 2., 3.])

In [71]:
int_tensor = torch.tensor([1,2,3],dtype=torch.int32)

In [72]:
int_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [73]:
bool_tensor = torch.tensor([1,0,1],dtype= torch.bool)

In [74]:
bool_tensor

tensor([ True, False,  True])

In [75]:
shape= torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [76]:
shape

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
shape.shape

torch.Size([3, 3])

In [78]:
shape.ndim

2

In [79]:
base_tensor = torch.ones(2,3)

In [80]:
base_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [81]:
zeros_like_tensor = torch.zeros_like(base_tensor)

In [82]:
zeros_like_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [83]:
random_like_tensor = torch.rand_like(base_tensor)

In [84]:
random_like_tensor

tensor([[0.6578, 0.0204, 0.7026],
        [0.3587, 0.0150, 0.5223]])

In [85]:
identiy_matrix= torch.eye(4)

In [86]:
identiy_matrix

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [87]:
fill_tensor = torch.full((2,3),7)

In [88]:
fill_tensor

tensor([[7, 7, 7],
        [7, 7, 7]])

In [91]:
tensor_a = torch.tensor([1.0,2.0,3.0])
tensor_b = torch.tensor([4.0, 5.0, 6.0])


In [92]:
sum_tensor = tensor_a+tensor_b

In [93]:
sum_tensor

tensor([5., 7., 9.])

In [94]:
sub_tensor = tensor_a-tensor_b

In [95]:
sub_tensor

tensor([-3., -3., -3.])

In [96]:
prod_tensor = tensor_a*tensor_b
prod_tensor

tensor([ 4., 10., 18.])

In [97]:
dib_tensor =  tensor_a/tensor_b
dib_tensor

tensor([0.2500, 0.4000, 0.5000])

In [98]:
tensor_a.add_(tensor_b)

tensor([5., 7., 9.])

In [99]:
tensor_a.mul_(tensor_b)

tensor([20., 35., 54.])

In [100]:
tensor_c = torch.tensor([1.0,2.0,3.0])

In [101]:
tensor_d = torch.tensor([[1.0],[2.0]])

In [102]:
broadcast_result = tensor_c +tensor_d

In [103]:
broadcast_result

tensor([[2., 3., 4.],
        [3., 4., 5.]])

In [104]:
matrix_a = torch.tensor([[1, 2,3], [3, 4,6]])
matrix_b = torch.tensor([[1, 2], [3, 4],[5, 6]])

In [105]:
matrix_mul_res = torch.matmul(matrix_a,matrix_b)

In [106]:
matrix_mul_res

tensor([[22, 28],
        [45, 58]])

In [107]:
vector_a = torch.tensor([1,2,3])
vector_b = torch.tensor([4, 5, 6])


In [108]:
dot_prod = torch.dot(vector_a,vector_b)

In [109]:
dot_prod

tensor(32)

In [111]:
tensor_e = torch.arange(9)

In [112]:
tensor_e

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
reshape_e = tensor_e.view(3,3)

In [114]:
reshape_e

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [115]:
reshape_e.shape

torch.Size([3, 3])

In [117]:
flattend_tensor = reshape_e.view(-1)

In [118]:
flattend_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
flattend_tensor.shape

torch.Size([9])

In [120]:
tensor_g= torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_h= torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [121]:
tensor_g

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [122]:
tensor_h

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [123]:
concat_rows = torch.cat((tensor_g,tensor_h))

In [124]:
concat_rows

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [125]:
concat_rows.shape

torch.Size([6, 3])

In [126]:
concat_cols= torch.cat((tensor_g,tensor_h), dim=1)

In [127]:
concat_cols

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]])

In [128]:
concat_cols.shape

torch.Size([3, 6])

In [129]:
tensor_g.ndim

2

In [130]:
element = tensor_g[1,2]

In [131]:
element

tensor(6)

In [133]:
tensor_g[2,1] = 100

In [134]:
tensor_g

tensor([[  1,   2,   3],
        [  4,   5,   6],
        [  7, 100,   9]])

In [135]:
sub_tensor  = tensor_g[:2,:2]

In [136]:
sub_tensor

tensor([[1, 2],
        [4, 5]])

In [138]:
second_row = tensor_g[1,:]

In [139]:
second_row

tensor([4, 5, 6])

In [140]:
third_col= tensor_g[:,2]

In [141]:
third_col

tensor([3, 6, 9])

In [142]:
step_rows  = tensor_g[::2,:]

In [143]:
step_rows

tensor([[  1,   2,   3],
        [  7, 100,   9]])

In [144]:
step_cols  = tensor_g[:,::2]

In [146]:
step_cols

tensor([[1, 3],
        [4, 6],
        [7, 9]])

In [147]:
mask =  tensor_g >5

In [148]:
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [149]:
masked_tensor  =  tensor_g[mask]

In [150]:
masked_tensor

tensor([  6,   7, 100,   9])

In [151]:
tensor_g

tensor([[  1,   2,   3],
        [  4,   5,   6],
        [  7, 100,   9]])

In [152]:
tensor_j= torch.tensor([1,2,3,4,5,6,7,8,9])

In [153]:
indiecs =  torch.tensor([0,2,4])

In [154]:
indiecs

tensor([0, 2, 4])

In [155]:
selected_elements = tensor_j[indiecs]

In [157]:
selected_elements

tensor([1, 3, 5])

In [158]:
tensor_h

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [159]:
row_indicies = torch.tensor([0,1,2])

In [160]:
col_indicies = torch.tensor([2,1,0])

In [161]:
selected_elements_2d = tensor_h[row_indicies,col_indicies]

In [162]:
selected_elements_2d

tensor([3, 5, 7])

## Automatic Difefernciation

In [ ]:
x = torch.tensor([])